plants ={	"flowers:rose",
		"flowers:tulip",
		"flowers:dandelion_yellow",
		"flowers:geranium",
		"flowers:viola",
		"flowers:dandelion_white",
		"flowers:mushroom_red",
		"flowers:mushroom_brown", 
		"default:dry_grass_1", 
		"default:dry_shrub",
 		"default:junglegrass",
		"default:grass_1",
		"farming:seed_cotton",
		"farming:seed_wheat",
		"default:acacia_bush_sapling",
		"default:acacia_bush_stem",
		"default:aspen_sapling",
		"default:acacia_bush_leaves",
		"default:acacia_leaves",
		"default:bush_leaves",
		"default:bush_sapling",
		"default:bush_stem",
		"default:cactus",
		"default:acacia_sapling",
		"default:jungleleaves",
		"default:junglesapling",
		"default:leaves",
		"default:papyrus",
		"default:pine_needles",
		"default:pine_sapling",
		"default:sapling",
		"flowers:waterlily",
		"default:aspen_leaves"
		
}

